module.exports.LETTER_TYPE = {EMP_LETTER:"EMP_LETTER",REC_LETTER:"REC_LETTER",
    ORG_DEGREE:"ORG_DEGREE",STUD_COPY:"STUD_COPY",OFFICIAL_TRANSCRIPT:"OFFICIAL_TRANSCRIPT"};
module.exports.ROLE_TYPE = {ADMIN:"ADMIN",STAFF:"STAFF",STUDENT:"STUDENT",ALUMNI:"ALUMNI"};
